<?xml version="1.0" encoding="UTF-8"?>
<matchInfo>
	<Img></Img>
	<name>炉石杯</name>
	<matchId>10023</matchId>
	<deadline>2017/4/11</deadline>
	<teamNum>36</teamNum>
	<personNum>1</personNum>
	<ruleId>1</ruleId>
	<award>20000</award>
	<organizerID>102</organizerID>
	<area>国服</area>
</matchInfo> 
<matchCommentList>
	<matchComment>
		<personId>001</personId>
		<date>2017/3/28/17:22:56</date>
		<commentContent>我报名了</commentContent>
	</matchComment>
	<matchComment>
		<personId>001</personId>
		<date>2017/3/28/17:22:56</date>
		<commentContent>我报名了</commentContent>
	</matchComment>
	<matchComment>
		<personId>001</personId>
		<date>2017/3/28/17:22:56</date>
		<commentContent>我报名了</commentContent>
	</matchComment>
</matchCommentList>